name: build_docker

on:
  push:
    branches: [master]
    tags:
      - '*.*.*'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout commit"
        uses: actions/checkout@v2

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1

      - name: "Set up Docker Buildx"
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: "Login to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "build docker images"
        run: |
          DOCKER_REPO="home-automation-frontend"
          DOCKER_ACC="dankersw"
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            GITHUB_TAG=${GITHUB_REF#refs/tags/*/}
            readarray -d / -t TAG_PATH <<< "$GITHUB_TAG"
            GIT_TAG="${TAG_PATH[2]}"
            echo "Building AMD64 and ARM64 for tag $GIT_TAG"
            IMG_TAG="$GIT_TAG"
          else
            echo "Building amd64 & arm64 for tag latest"
            IMG_TAG="latest"
          fi
          docker buildx build -t $DOCKER_ACC/$DOCKER_REPO:$IMG_TAG . --build-arg tag=$IMG_TAG --platform linux/amd64,linux/arm64 --push